const questions = [
  { level: 1, question: 'What is the primary purpose of a firewall?', option1: 'To encrypt data in transit', option2: 'To block unauthorized network access', option3: 'To store user passwords securely', option4: 'To manage software updates', correct_answer: 'To block unauthorized network access', explanation: 'Firewalls are network security devices that monitor and filter incoming and outgoing network traffic based on security rules.' },
  { level: 1, question: 'Which of these is a common form of social engineering?', option1: 'SQL injection', option2: 'DDoS attack', option3: 'Phishing email', option4: 'Port scanning', correct_answer: 'Phishing email', explanation: 'Phishing uses fraudulent messages to trick people into revealing sensitive data or installing malware.' },
  { level: 1, question: 'What does HTTPS provide that HTTP does not?', option1: 'Data compression', option2: 'Server load balancing', option3: 'Encryption of data in transit', option4: 'Faster database queries', correct_answer: 'Encryption of data in transit', explanation: 'HTTPS uses TLS/SSL to encrypt communication between the client and server, protecting against eavesdropping.' },
  { level: 1, question: 'A strong password should include which of the following?', option1: 'Only lowercase letters', option2: 'A dictionary word', option3: 'A mix of letters, numbers, and symbols', option4: 'Your username', correct_answer: 'A mix of letters, numbers, and symbols', explanation: 'Strong passwords are long and use varied character types to reduce the chance of being guessed or brute-forced.' },
  { level: 1, question: 'What is two-factor authentication (2FA)?', option1: 'Using two passwords at login', option2: 'A second copy of user data', option3: 'A second verification step beyond a password', option4: 'Encryption of two files', correct_answer: 'A second verification step beyond a password', explanation: '2FA adds an extra authentication factor, such as a code or biometric, in addition to a password.' },
  { level: 1, question: 'Which action improves security when using public Wi-Fi?', option1: 'Disable the firewall', option2: 'Use a VPN', option3: 'Share files with everyone', option4: 'Install random apps', correct_answer: 'Use a VPN', explanation: 'A VPN encrypts traffic over public networks, making it harder for attackers to intercept sensitive data.' },
  { level: 1, question: 'What is malware?', option1: 'Hardware device for backups', option2: 'Software designed to harm systems or data', option3: 'A web browser extension', option4: 'A cloud storage provider', correct_answer: 'Software designed to harm systems or data', explanation: 'Malware is malicious software created to damage, disrupt, or gain unauthorized access to systems.' },
  { level: 1, question: 'Which of the following is a sign of a phishing attempt?', option1: 'Email from a known contact with no links', option2: 'Unexpected request for credentials', option3: 'Simple website layout', option4: 'Email with proper grammar only', correct_answer: 'Unexpected request for credentials', explanation: 'Phishing messages often ask for passwords, personal data, or financial information unexpectedly.' },
  { level: 1, question: 'What does the principle of least privilege mean?', option1: 'Give all users admin access', option2: 'Limit access rights to only what is needed', option3: 'Share credentials with coworkers', option4: 'Use the same password everywhere', correct_answer: 'Limit access rights to only what is needed', explanation: 'Least privilege reduces risk by restricting permissions to the minimum necessary for a task.' },
  { level: 1, question: 'Which of these is a secure way to store passwords?', option1: 'Plain text file', option2: 'Encrypted archive', option3: 'Hashed with salt', option4: 'Printed on paper', correct_answer: 'Hashed with salt', explanation: 'Passwords should be hashed with a strong salt so they cannot be reversed if the database is compromised.' },
  { level: 2, question: 'What is the main goal of a penetration test?', option1: 'Design a new network', option2: 'Evaluate security by simulating attacks', option3: 'Train employees on software', option4: 'Encrypt all files', correct_answer: 'Evaluate security by simulating attacks', explanation: 'Penetration testing assesses security weaknesses by attempting to exploit them in a controlled way.' },
  { level: 2, question: 'Which protocol is used to securely transfer files over SSH?', option1: 'FTP', option2: 'SCP', option3: 'HTTP', option4: 'SMTP', correct_answer: 'SCP', explanation: 'SCP (Secure Copy) transfers files securely over an SSH connection.' },
  { level: 2, question: 'What is a VPN primarily used for?', option1: 'Reducing network latency', option2: 'Securely connecting to a remote network', option3: 'Scanning for malware', option4: 'Faster streaming', correct_answer: 'Securely connecting to a remote network', explanation: 'A VPN creates an encrypted tunnel between your device and a remote network, protecting traffic in transit.' },
  { level: 2, question: 'Which type of attack overloads a service with requests?', option1: 'Man-in-the-middle', option2: 'DDoS', option3: 'SQL injection', option4: 'Brute force', correct_answer: 'DDoS', explanation: 'A Distributed Denial of Service attack floods a target with traffic to make it unavailable.' },
  { level: 2, question: 'What is the purpose of an intrusion detection system (IDS)?', option1: 'Detect suspicious activity', option2: 'Encrypt email', option3: 'Backup databases', option4: 'Manage user permissions', correct_answer: 'Detect suspicious activity', explanation: 'IDS tools monitor networks or systems for signs of unauthorized or malicious behavior.' },
  { level: 2, question: 'Which term describes hidden malicious code that executes when conditions are met?', option1: 'Trojan', option2: 'Logic bomb', option3: 'Worm', option4: 'Spyware', correct_answer: 'Logic bomb', explanation: 'A logic bomb is malware triggered by a specific event or condition, such as a date or system state.' },
  { level: 2, question: 'What does SQL injection exploit?', option1: 'Weak encryption algorithms', option2: 'Unvalidated user input in database queries', option3: 'HTTP headers', option4: 'Firewall rules', correct_answer: 'Unvalidated user input in database queries', explanation: 'SQL injection occurs when attackers insert malicious SQL into queries due to improper input validation.' },
  { level: 2, question: 'Which layer of the OSI model handles routing between networks?', option1: 'Data Link', option2: 'Transport', option3: 'Network', option4: 'Presentation', correct_answer: 'Network', explanation: 'The Network layer is responsible for packet forwarding and routing across network boundaries.' },
  { level: 2, question: 'What is the main benefit of network segmentation?', option1: 'Faster downloads', option2: 'Stronger encryption', option3: 'Reduce attack surface and contain breaches', option4: 'Simpler passwords', correct_answer: 'Reduce attack surface and contain breaches', explanation: 'Segmenting a network limits attacker movement by isolating systems and enforcing stricter controls.' },
  { level: 2, question: 'Which security control prevents unauthorized modification of data?', option1: 'Integrity control', option2: 'Availability control', option3: 'Confidentiality control', option4: 'Authentication control', correct_answer: 'Integrity control', explanation: 'Integrity controls ensure that data remains accurate and unaltered except by authorized processes.' },
  { level: 3, question: 'What does MFA stand for?', option1: 'Multiple File Access', option2: 'Multi-Factor Authentication', option3: 'Minimal Firewall Access', option4: 'Managed File Archive', correct_answer: 'Multi-Factor Authentication', explanation: 'MFA requires two or more different authentication factors to verify identity.' },
  { level: 3, question: 'Which attack captures traffic between two parties?', option1: 'Phishing', option2: 'Man-in-the-middle', option3: 'Spoofing', option4: 'Ransomware', correct_answer: 'Man-in-the-middle', explanation: 'A man-in-the-middle attack intercepts and possibly alters communications between two systems.' },
  { level: 3, question: 'What is the primary purpose of hashing passwords?', option1: 'Compressing data for storage', option2: 'Making passwords retrievable', option3: 'Verifying password authenticity without storing plain text', option4: 'Encrypting network traffic', correct_answer: 'Verifying password authenticity without storing plain text', explanation: 'Hashes allow password verification while keeping the actual password hidden from the system.' },
  { level: 3, question: 'Which of the following is a common indicator of a compromised email account?', option1: 'Sent messages you did not send', option2: 'Fewer emails than normal', option3: 'Faster inbox searches', option4: 'No attachments', correct_answer: 'Sent messages you did not send', explanation: 'Unauthorized sent messages often mean an attacker is using the compromised email account.' },
  { level: 3, question: 'What is the safest action when receiving an unexpected attachment?', option1: 'Open it immediately', option2: 'Delete it without checking', option3: 'Verify sender and scan with antivirus', option4: 'Forward it to others', correct_answer: 'Verify sender and scan with antivirus', explanation: 'Unexpected attachments may contain malware, so verify legitimacy before opening.' },
  { level: 3, question: 'Which is a recommended way to patch vulnerabilities?', option1: 'Ignore low-severity updates', option2: 'Apply vendor security updates promptly', option3: 'Use unsupported software', option4: 'Disconnect permanently', correct_answer: 'Apply vendor security updates promptly', explanation: 'Timely patching reduces exposure to known vulnerabilities and active exploits.' },
  { level: 3, question: 'What is a digital certificate used for?', option1: 'Storing user passwords', option2: 'Authenticating identities and enabling encryption', option3: 'Backing up files', option4: 'Blocking network traffic', correct_answer: 'Authenticating identities and enabling encryption', explanation: 'Digital certificates prove identity and help establish secure encrypted connections.' },
  { level: 3, question: 'Which of the following best describes ransomware?', option1: 'Malware that encrypts files and demands payment', option2: 'Tool for penetration testing', option3: 'Backup software', option4: 'Network monitoring system', correct_answer: 'Malware that encrypts files and demands payment', explanation: 'Ransomware locks or encrypts data and requires payment for restoration.' },
  { level: 3, question: 'What is the most secure way to transmit sensitive data?', option1: 'Unencrypted email', option2: 'Encrypted connection such as HTTPS or TLS', option3: 'Public file sharing link', option4: 'Social media message', correct_answer: 'Encrypted connection such as HTTPS or TLS', explanation: 'Encryption protects sensitive data from interception during transmission.' },
  { level: 3, question: 'What does patch management help prevent?', option1: 'Unauthorized physical access', option2: 'Outdated software vulnerabilities', option3: 'Password reuse', option4: 'Insider threats', correct_answer: 'Outdated software vulnerabilities', explanation: 'Patch management keeps software updated to reduce security risks from known flaws.' },
  { level: 4, question: 'What is a zero-day vulnerability?', option1: 'A bug fixed before release', option2: 'A vulnerability known to attackers before a patch exists', option3: 'A malware variant that runs for one day', option4: 'A backup schedule', correct_answer: 'A vulnerability known to attackers before a patch exists', explanation: 'Zero-day flaws are exploited before developers can provide a patch, making them especially dangerous.' },
  { level: 4, question: 'What is the purpose of a security audit?', option1: 'Design a new logo', option2: 'Assess compliance and identify risks', option3: 'Encrypt disk drives', option4: 'Write user documentation', correct_answer: 'Assess compliance and identify risks', explanation: 'Security audits evaluate controls and practices to ensure systems follow policies and standards.' },
  { level: 4, question: 'Which tool is used to examine network traffic in detail?', option1: 'Wireshark', option2: 'Text editor', option3: 'Spreadsheet', option4: 'Antivirus scanner', correct_answer: 'Wireshark', explanation: 'Wireshark captures and inspects network packets for analysis and troubleshooting.' },
  { level: 4, question: 'What is DNS spoofing?', option1: 'Stealing email attachments', option2: 'Altering DNS responses to redirect traffic', option3: 'Encrypting DNS records', option4: 'Blocking DNS requests', correct_answer: 'Altering DNS responses to redirect traffic', explanation: 'DNS spoofing tricks devices into visiting malicious sites by falsifying DNS replies.' },
  { level: 4, question: 'Which is a principle of secure software development?', option1: 'Write code without review', option2: 'Use hard-coded credentials', option3: 'Validate all input and handle errors safely', option4: 'Disable logging', correct_answer: 'Validate all input and handle errors safely', explanation: 'Secure development practices include input validation, error handling, and avoiding hard-coded secrets.' },
  { level: 4, question: 'What does the CIA triad stand for in cybersecurity?', option1: 'Confidentiality, Integrity, Availability', option2: 'Control, Identification, Authentication', option3: 'Cookies, IP, ASN', option4: 'Compliance, Insurance, Audit', correct_answer: 'Confidentiality, Integrity, Availability', explanation: 'The CIA triad is a core security model representing data protection goals.' },
  { level: 4, question: 'Which term describes a network device that separates different network zones?', option1: 'Router', option2: 'Firewall', option3: 'Modem', option4: 'Switch', correct_answer: 'Firewall', explanation: 'Firewalls control traffic between network segments and enforce security policies.' },
  { level: 4, question: 'What is the main value of a security policy?', option1: 'Specify allowed and prohibited behavior', option2: 'Guarantee no breaches', option3: 'Replace antivirus software', option4: 'Create faster networks', correct_answer: 'Specify allowed and prohibited behavior', explanation: 'Security policies define rules and expectations for protecting systems and data.' },
  { level: 4, question: 'What is the most secure way to dispose of sensitive physical media?', option1: 'Throw in trash', option2: 'Shred or degauss it', option3: 'Leave it in a drawer', option4: 'Reuse it without wiping', correct_answer: 'Shred or degauss it', explanation: 'Physical destruction prevents recovered media from being read by attackers.' },
  { level: 4, question: 'Which is an example of multifactor authentication?', option1: 'Password and password hint', option2: 'Password and SMS code', option3: 'Username and password', option4: 'Security question only', correct_answer: 'Password and SMS code', explanation: 'Using something you know plus something you have increases authentication security.' },
  { level: 5, question: 'What is the main risk of using default credentials?', option1: 'They expire quickly', option2: 'Attackers can easily guess them', option3: 'They are too complex', option4: 'They slow down systems', correct_answer: 'Attackers can easily guess them', explanation: 'Default credentials are widely known and should always be changed before production use.' },
  { level: 5, question: 'In a public key infrastructure, what does the private key do?', option1: 'Encrypt outgoing messages only', option2: 'Decrypt messages sent to the key owner', option3: 'Sign certificates for others', option4: 'Become public information', correct_answer: 'Decrypt messages sent to the key owner', explanation: 'The private key stays secret and is used to decrypt data or sign messages.' },
  { level: 5, question: 'What is an attack surface?', option1: 'Only physical doors to a building', option2: 'All points where an attacker can try to compromise a system', option3: 'The screen size of a device', option4: 'The number of users', correct_answer: 'All points where an attacker can try to compromise a system', explanation: 'Attack surface includes software, network, hardware, and human elements exposed to threats.' },
  { level: 5, question: 'Which technology helps protect data at rest?', option1: 'Disk encryption', option2: 'Public Wi-Fi', option3: 'Text messaging', option4: 'Cached web pages', correct_answer: 'Disk encryption', explanation: 'Encrypting storage protects data when devices are powered off or stolen.' },
  { level: 5, question: 'What is the purpose of account lockout after failed logins?', option1: 'Prevent user access permanently', option2: 'Protect against brute-force attacks', option3: 'Speed up login time', option4: 'Create more user accounts', correct_answer: 'Protect against brute-force attacks', explanation: 'Lockout policies limit repeated login attempts and deter automated password guessing.' },
  { level: 5, question: 'Which control helps detect unauthorized file changes?', option1: 'Change management', option2: 'File integrity monitoring', option3: 'Background music', option4: 'Clipboard sharing', correct_answer: 'File integrity monitoring', explanation: 'File integrity monitoring checks files for unexpected changes that may indicate compromise.' },
  { level: 5, question: 'What is the role of a Certificate Authority (CA)?', option1: 'Issue digital certificates', option2: 'Host websites', option3: 'Repair hardware', option4: 'Manage passwords', correct_answer: 'Issue digital certificates', explanation: 'CAs validate identities and sign certificates used for secure communication.' },
  { level: 5, question: 'Which of the following is a sign of a weak security policy?', option1: 'Regular training and testing', option2: 'Unclear user responsibilities', option3: 'Consistent enforcement', option4: 'Defined incident response', correct_answer: 'Unclear user responsibilities', explanation: 'Policies should clearly describe roles and expectations to be effective.' },
  { level: 5, question: 'What is the benefit of disabling unused services?', option1: 'Improve security by reducing potential vulnerabilities', option2: 'Increase power consumption', option3: 'Create more user accounts', option4: 'Make systems slower', correct_answer: 'Improve security by reducing potential vulnerabilities', explanation: 'Unused services can provide extra attack vectors, so disabling them lowers risk.' },
  { level: 5, question: 'What is the purpose of a password manager?', option1: 'Store passwords securely and generate random passwords', option2: 'Share passwords with coworkers', option3: 'Auto-fill passwords in public', option4: 'Disable MFA', correct_answer: 'Store passwords securely and generate random passwords', explanation: 'Password managers help users create and store strong unique passwords for each account.' },
  { level: 6, question: 'What is the main difference between brute-force and dictionary attacks?', option1: 'Dictionary attacks try common passwords, brute-force tries all combinations', option2: 'Brute-force uses social engineering', option3: 'Dictionary attacks work only on networks', option4: 'Brute-force uses encryption', correct_answer: 'Dictionary attacks try common passwords, brute-force tries all combinations', explanation: 'A dictionary attack uses a list of likely passwords while brute-force attempts every possible combination.' },
  { level: 6, question: 'Which policy is generally more secure?', option1: 'Blacklist', option2: 'Whitelist', option3: 'No policy', option4: 'Default allow', correct_answer: 'Whitelist', explanation: 'A whitelist allows only known good items, reducing exposure compared to blocking known bad items.' },
  { level: 6, question: 'What is the first step in incident response?', option1: 'Recovery', option2: 'Containment', option3: 'Identification', option4: 'Eradication', correct_answer: 'Identification', explanation: 'Incident response begins with identifying and confirming that an event is occurring.' },
  { level: 6, question: 'Which attack injects malicious code into a web page to run in a victim browser?', option1: 'Phishing', option2: 'SQL injection', option3: 'Cross-site scripting', option4: 'Brute force', correct_answer: 'Cross-site scripting', explanation: 'XSS inserts scripts into pages viewed by other users, often stealing cookies or session data.' },
  { level: 6, question: 'What does an access control list (ACL) define?', option1: 'Network topology', option2: 'User password strength', option3: 'Which subjects may access which objects', option4: 'Backup schedule', correct_answer: 'Which subjects may access which objects', explanation: 'ACLs specify permissions for users or systems to access resources.' },
  { level: 6, question: 'What is a side-channel attack?', option1: 'Attack based on physical data leakage such as timing or power usage', option2: 'Attack on a social media account', option3: 'Brute-force attack on a password', option4: 'Database injection', correct_answer: 'Attack based on physical data leakage such as timing or power usage', explanation: 'Side-channel attacks exploit indirect information from a system to infer secrets.' },
  { level: 6, question: 'What does a default-deny firewall rule do?', option1: 'Allow all traffic by default', option2: 'Block all traffic unless explicitly allowed', option3: 'Log all traffic without blocking it', option4: 'Disable the firewall', correct_answer: 'Block all traffic unless explicitly allowed', explanation: 'Default deny ensures only known and permitted traffic can pass the firewall.' },
  { level: 6, question: 'What is a supply chain attack?', option1: 'Attack against physical doors', option2: 'Malicious code introduced through trusted software or hardware suppliers', option3: 'Using weak passwords', option4: 'Stealing user credentials locally', correct_answer: 'Malicious code introduced through trusted software or hardware suppliers', explanation: 'Supply chain attacks compromise vendors or third-party components used by the target.' },
  { level: 6, question: 'What is the principle of separation of duties?', option1: 'One person performs all security tasks', option2: 'Different people handle different parts of a process to prevent abuse', option3: 'Store all credentials together', option4: 'Use one account for everyone', correct_answer: 'Different people handle different parts of a process to prevent abuse', explanation: 'Separation of duties reduces fraud and mistakes by distributing responsibilities.' },
  { level: 6, question: 'What is secure boot designed to do?', option1: 'Boot faster', option2: 'Ensure only trusted software runs during startup', option3: 'Disable antivirus', option4: 'Encrypt RAM', correct_answer: 'Ensure only trusted software runs during startup', explanation: 'Secure boot verifies boot components against trusted signatures before execution.' },
  { level: 7, question: 'What is the purpose of a security token in authentication?', option1: 'Store encryption keys publicly', option2: 'Prove identity during login without a password', option3: 'Replace antivirus software', option4: 'Monitor network traffic', correct_answer: 'Prove identity during login without a password', explanation: 'Security tokens provide a second factor or passwordless authentication method.' },
  { level: 7, question: 'What is the difference between salt and pepper in password hashing?', option1: 'Salt is public and unique per password, pepper is secret and global', option2: 'Salt is a type of malware', option3: 'Pepper is used in encryption only', option4: 'Salt makes passwords shorter', correct_answer: 'Salt is public and unique per password, pepper is secret and global', explanation: 'Salt prevents precomputed hash attacks; pepper adds a secret value known only to the server.' },
  { level: 7, question: 'What is the most important reason to rotate encryption keys regularly?', option1: 'Reduce chance of key compromise affecting data long-term', option2: 'Make backups larger', option3: 'Increase CPU usage', option4: 'Avoid password expiration', correct_answer: 'Reduce chance of key compromise affecting data long-term', explanation: 'Key rotation limits the amount of data exposed if a key is compromised.' },
  { level: 7, question: 'What does data classification help organizations do?', option1: 'Encrypt all data the same way', option2: 'Identify sensitivity levels and apply appropriate protections', option3: 'Delete old files automatically', option4: 'Share data publicly', correct_answer: 'Identify sensitivity levels and apply appropriate protections', explanation: 'Classification ensures critical data receives stronger controls than public data.' },
  { level: 7, question: 'Why are logs important for security?', option1: 'They replace antivirus', option2: 'They provide evidence of events and support detection and investigation', option3: 'They slow down systems', option4: 'They encrypt files', correct_answer: 'They provide evidence of events and support detection and investigation', explanation: 'Logging enables monitoring, forensics, and auditing of security incidents.' },
  { level: 7, question: 'In secure coding, why validate input on the server?', option1: 'To improve user interface colors', option2: 'To prevent malicious data from reaching backend systems', option3: 'To make requests faster', option4: 'To reduce disk space', correct_answer: 'To prevent malicious data from reaching backend systems', explanation: 'Server-side validation is essential because client-side checks can be bypassed.' },
  { level: 7, question: 'What is a demilitarized zone (DMZ) in network architecture?', option1: 'An unsecured wireless network', option2: 'A network segment exposed to untrusted users while isolating internal systems', option3: 'A firewall setting', option4: 'A VPN type', correct_answer: 'A network segment exposed to untrusted users while isolating internal systems', explanation: 'A DMZ hosts public-facing services while keeping the internal network separate.' },
  { level: 7, question: 'What does threat modeling help security teams do?', option1: 'Calculate server costs', option2: 'Identify potential threats and design mitigations early', option3: 'Design user interfaces', option4: 'Repair damaged hardware', correct_answer: 'Identify potential threats and design mitigations early', explanation: 'Threat modeling evaluates how attackers could exploit a system so defenses can be built proactively.' },
  { level: 7, question: 'Which is an example of a detective control?', option1: 'Firewall rule', option2: 'Intrusion detection system', option3: 'Encryption', option4: 'Access control policy', correct_answer: 'Intrusion detection system', explanation: 'Detective controls identify and alert on suspicious activity after it occurs.' },
  { level: 7, question: 'Why is biometrics considered a factor of authentication?', option1: 'It uses something you have', option2: 'It uses something you know', option3: 'It uses something you are', option4: 'It uses something you saw', correct_answer: 'It uses something you are', explanation: 'Biometrics rely on physical or behavioral characteristics unique to the user.' },
  { level: 8, question: 'What does SIEM stand for?', option1: 'Security Information and Event Management', option2: 'Secure Internet Email Method', option3: 'System Integrity Evaluation Model', option4: 'Software Installation Event Monitor', correct_answer: 'Security Information and Event Management', explanation: 'SIEM solutions aggregate logs and alerts to help detect and respond to security incidents.' },
  { level: 8, question: 'What is the difference between a vulnerability and an exploit?', option1: 'A vulnerability is a weakness, an exploit is a way to take advantage of it', option2: 'A vulnerability is malware, an exploit is a patch', option3: 'An exploit is a user password', option4: 'A vulnerability is always public', correct_answer: 'A vulnerability is a weakness, an exploit is a way to take advantage of it', explanation: 'Vulnerabilities are flaws, while exploits are techniques or code that use those flaws.' },
  { level: 8, question: 'What is a man-in-the-browser attack?', option1: 'Malware that intercepts browser activity to manipulate transactions', option2: 'Network packet sniffing', option3: 'A phishing website', option4: 'A browser update', correct_answer: 'Malware that intercepts browser activity to manipulate transactions', explanation: 'Man-in-the-browser malware operates inside the browser to alter pages or steal credentials.' },
  { level: 8, question: 'What kind of vulnerability does a buffer overflow exploit?', option1: 'Weak encryption key', option2: 'Writing more data than a buffer can hold', option3: 'Wrong password', option4: 'Broken SSL certificate', correct_answer: 'Writing more data than a buffer can hold', explanation: 'Buffer overflows happen when software fails to check the size of input data and overwrites memory.' },
  { level: 8, question: 'Why is certificate expiration important for HTTPS?', option1: 'Expired certificates signal possible trust issues or misconfiguration', option2: 'They improve page speed', option3: 'They encrypt data better after expiration', option4: 'They reduce bandwidth', correct_answer: 'Expired certificates signal possible trust issues or misconfiguration', explanation: 'Certificates must be valid to confirm the site identity and secure the connection.' },
  { level: 8, question: 'What is password entropy a measure of?', option1: 'User popularity', option2: 'Difficulty of guessing a password', option3: 'Network bandwidth', option4: 'CPU usage', correct_answer: 'Difficulty of guessing a password', explanation: 'Entropy indicates how unpredictable a password is, which affects its strength.' },
  { level: 8, question: 'What is remote code execution (RCE)?', option1: 'Running code only on a local machine', option2: 'Attackers executing code on a remote system', option3: 'Encrypting code remotely', option4: 'Downloading software updates', correct_answer: 'Attackers executing code on a remote system', explanation: 'RCE vulnerabilities allow attackers to execute arbitrary commands on affected systems.' },
  { level: 8, question: 'What is a honeypot used for?', option1: 'Attract and study attackers in a controlled environment', option2: 'Store encrypted passwords', option3: 'Accelerate downloads', option4: 'Backup data', correct_answer: 'Attract and study attackers in a controlled environment', explanation: 'Honeypots are decoy systems designed to lure attackers and learn their behavior.' },
  { level: 8, question: 'Which encryption method uses separate keys for encrypting and decrypting?', option1: 'Symmetric encryption', option2: 'Asymmetric encryption', option3: 'Hashing', option4: 'Base64', correct_answer: 'Asymmetric encryption', explanation: 'Asymmetric cryptography uses a public key and a private key for different operations.' },
  { level: 8, question: 'What is sandboxing?', option1: 'Running code in a restricted environment to limit damage', option2: 'Encrypting files on disk', option3: 'A type of firewall', option4: 'A user training method', correct_answer: 'Running code in a restricted environment to limit damage', explanation: 'Sandboxes isolate applications so malicious or buggy code cannot harm the host system.' },
  { level: 9, question: 'Why are memory-safe languages useful for security?', option1: 'They prevent many common memory errors like buffer overflows', option2: 'They run faster always', option3: 'They require no testing', option4: 'They bypass encryption', correct_answer: 'They prevent many common memory errors like buffer overflows', explanation: 'Memory safety helps avoid vulnerabilities caused by unsafe pointer or buffer handling.' },
  { level: 9, question: 'What does zero trust architecture assume?', option1: 'All users are trusted by default', option2: 'No user or device is trusted without verification', option3: 'Only internal networks are unsafe', option4: 'VPNs are unnecessary', correct_answer: 'No user or device is trusted without verification', explanation: 'Zero trust continuously verifies identities and devices before granting access.' },
  { level: 9, question: 'What is the main goal of data breach notification laws?', option1: 'Delay reporting breaches', option2: 'Inform affected parties and authorities quickly', option3: 'Hide security incidents', option4: 'Reduce encryption costs', correct_answer: 'Inform affected parties and authorities quickly', explanation: 'Breach notification requirements help victims respond and regulators investigate promptly.' },
  { level: 9, question: 'Which security control is corrective?', option1: 'Antivirus updating', option2: 'Restoring from backups after an incident', option3: 'Firewall blocking', option4: 'Access logging', correct_answer: 'Restoring from backups after an incident', explanation: 'Corrective controls fix or restore systems after a security event.' },
  { level: 9, question: 'What is the purpose of a phishing simulation?', option1: 'Test employee awareness and improve training', option2: 'Infect users with malware', option3: 'Encrypt email', option4: 'Monitor network throughput', correct_answer: 'Test employee awareness and improve training', explanation: 'Simulations help organizations evaluate how users respond to suspicious emails and reinforce security behavior.' },
  { level: 9, question: 'What does CVE stand for?', option1: 'Common Vulnerabilities and Exposures', option2: 'Central Vendor Exchange', option3: 'Certified Virus Example', option4: 'Cybersecurity Verification Event', correct_answer: 'Common Vulnerabilities and Exposures', explanation: 'CVE is a standardized identifier for publicly disclosed cybersecurity vulnerabilities.' },
  { level: 9, question: 'How is hashing different from encryption?', option1: 'Hashing is one-way, encryption is reversible with a key', option2: 'Hashing uses public keys only', option3: 'Encryption is always insecure', option4: 'Hashing stores user passwords in plain text', correct_answer: 'Hashing is one-way, encryption is reversible with a key', explanation: 'Hashes cannot be reversed to get the original value, while encrypted data can be decrypted with the correct key.' },
  { level: 9, question: 'What is DMARC used for?', option1: 'Authenticate DNS records', option2: 'Help prevent email spoofing and phishing', option3: 'Encrypt email content', option4: 'Manage firewall rules', correct_answer: 'Help prevent email spoofing and phishing', explanation: 'DMARC helps domain owners specify which email sources are authorized and how receivers should handle failures.' },
  { level: 9, question: 'What is the difference between vulnerability scanning and penetration testing?', option1: 'Scanning is automated identification, penetration testing is active exploitation', option2: 'Scanning takes longer than penetration testing', option3: 'Penetration testing uses only antivirus software', option4: 'Scanning always exploits vulnerabilities', correct_answer: 'Scanning is automated identification, penetration testing is active exploitation', explanation: 'Vulnerability scans discover issues; penetration tests verify whether they can be exploited.' },
  { level: 10, question: 'What is the main role of a Chief Information Security Officer (CISO)?', option1: 'Run daily backup jobs', option2: 'Lead cybersecurity strategy and risk management', option3: 'Deploy network cables', option4: 'Write application code', correct_answer: 'Lead cybersecurity strategy and risk management', explanation: 'The CISO defines security policies, oversees controls, and manages enterprise cyber risk.' },
  { level: 10, question: 'Why do organizations buy cyber insurance?', option1: 'To eliminate all security risk', option2: 'To transfer some financial risk from cyber incidents', option3: 'To replace firewalls', option4: 'To avoid patching', correct_answer: 'To transfer some financial risk from cyber incidents', explanation: 'Cyber insurance helps cover costs from breaches, outages, and liabilities after incidents.' },
  { level: 10, question: 'What is an Advanced Persistent Threat (APT)?', option1: 'A one-time random attack', option2: 'A prolonged, targeted intrusion by skilled adversaries', option3: 'A phishing email sent to many users', option4: 'A browser popup', correct_answer: 'A prolonged, targeted intrusion by skilled adversaries', explanation: 'APTs are stealthy, long-term attacks focused on high-value targets.' },
  { level: 10, question: 'What does immutability mean in blockchain security?', option1: 'Data cannot be changed once recorded', option2: 'Network packets never expire', option3: 'Passwords never change', option4: 'Logs are deleted automatically', correct_answer: 'Data cannot be changed once recorded', explanation: 'Blockchain immutability ensures records remain tamper-resistant after creation.' },
  { level: 10, question: 'What is the Secure Development Lifecycle (SDLC)?', option1: 'A process for integrating security throughout software development', option2: 'A database backup routine', option3: 'A network monitoring tool', option4: 'A firewall rule set', correct_answer: 'A process for integrating security throughout software development', explanation: 'SDLC embeds security checks from design through deployment to reduce vulnerabilities.' },
  { level: 10, question: 'Why is serverless architecture a security concern?', option1: 'It requires no authentication', option2: 'It can introduce new attack surfaces in function invocation and dependencies', option3: 'It always uses outdated libraries', option4: 'It cannot scale', correct_answer: 'It can introduce new attack surfaces in function invocation and dependencies', explanation: 'Serverless functions and managed services need secure configuration and dependency management.' },
  { level: 10, question: 'What is endpoint detection and response (EDR)?', option1: 'A tool that blocks all internet traffic', option2: 'A solution that monitors endpoints for suspicious activity and helps respond', option3: 'A firewall type', option4: 'A backup system', correct_answer: 'A solution that monitors endpoints for suspicious activity and helps respond', explanation: 'EDR collects data from endpoints to detect, investigate, and contain threats.' },
  { level: 10, question: 'What does privacy by design mean?', option1: 'Privacy is added after development', option2: 'Privacy is considered from the start of system design', option3: 'All data is made public', option4: 'Only passwords are encrypted', correct_answer: 'Privacy is considered from the start of system design', explanation: 'Privacy by design builds data protection into systems and processes from the beginning.' },
  { level: 10, question: 'What is security orchestration, automation, and response (SOAR)?', option1: 'Manual logging process', option2: 'Tools that automate security incident workflows and response', option3: 'A type of encryption algorithm', option4: 'A network cable standard', correct_answer: 'Tools that automate security incident workflows and response', explanation: 'SOAR platforms help teams automate repetitive security tasks and coordinate incident response.' },
  { level: 10, question: 'What is a distributed ledger?', option1: 'A centralized database', option2: 'A shared database where records are replicated across multiple participants', option3: 'A filesystem backup', option4: 'A type of VPN', correct_answer: 'A shared database where records are replicated across multiple participants', explanation: 'Distributed ledgers store data across many nodes to improve transparency and resilience.' },
  { level: 10, question: 'What is a security baseline?', option1: 'A standard configuration used to ensure consistent security settings', option2: 'A backup of logs', option3: 'A firewall rule set for public Wi-Fi', option4: 'An incident report', correct_answer: 'A standard configuration used to ensure consistent security settings', explanation: 'Security baselines help organizations enforce consistent, secure configurations across systems.' }
];

const seedQuestions = async (pool) => {
  try {
    const result = await pool.query('SELECT COUNT(*) FROM questions');
    const count = parseInt(result.rows[0].count, 10);

    if (count > 0) {
      console.log(`🔁 Seed skipped: ${count} questions already exist.`);
      return;
    }

    await pool.query('BEGIN');
    for (const q of questions) {
      await pool.query(
        'INSERT INTO questions (level, question, option1, option2, option3, option4, correct_answer, explanation) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
        [q.level, q.question, q.option1, q.option2, q.option3, q.option4, q.correct_answer, q.explanation]
      );
    }
    await pool.query('COMMIT');
    console.log(`✅ Seeded ${questions.length} questions.`);
  } catch (error) {
    await pool.query('ROLLBACK');
    console.error('❌ Failed to seed questions:', error.message);
  }
};

module.exports = seedQuestions;
 